Only one between pec and SDI code must be mandatory
webgriffe/SyliusItalianInvoiceableOrderPlugin pull request #4
Opened 2021-06-28 12:19 UTC by fabianaromagnoli

Solve issue #3

2021-06-28 13:02 UTC, lruozzi9 requested changes
While doing the review I also thought of another situation. If I'm not wrong, the Italian SDI system accepts the code '0000000' as a valid SDI code. By entering this code, however, the PEC address must be present. I think we should add this case as well.

2021-06-30 16:53 UTC, mmenozzi commented
We have to fix the Roave BC check...

2021-08-09 09:18 UTC, lruozzi9 approved these changes

2021-08-09 10:39 UTC, mmenozzi approved these changes

2021-08-09 10:39 UTC, mmenozzi commented on src/Resources/translations/validators+intl-icu.it.yaml
> +            required_if_sdi_is_null: 'Per favore, inserisci almeno uno tra codice SDI e indirizzo PEC'
I'd use the same message key.

2021-08-09 10:39 UTC, mmenozzi commented on src/Resources/translations/validators+intl-icu.en.yaml
> +            required_if_sdi_is_null: 'At least one between PEC address and SDI code is required'
I'd use the same message key

2021-08-09 10:56 UTC, lruozzi9 approved these changes

2021-08-09 10:57 UTC, merged